version: "3"

services:
  db:
    image: postgres:13
    container_name: matcha-db
    restart: on-failure
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - ./db:/var/lib/postgresql/data